### ISSUE TITLE
Steps to get this working - just some notes for README

### ISSUE THREAD

**Issue by designvoid** [dusterio/lumen-passport#1]
Hi there,

Thanks for putting this together - I have just spent the morning tinkering and trying to get this working with Lumen. I have got pretty far and thought it might help other if I put down some notes as to what I did in order to get the Password Grant option working.

1) I had to modify my minimum stability in the Lumen composer file and grab the latest dev branch

2) along with adding the included PassportServiceProvider I had to add:

    $app->register(Laravel\Passport\PassportServiceProvider::class);

3) also I needed to uncomment

    $app->withFacades();

    $app->withEloquent();

    $app->routeMiddleware([
        'auth' => App\Http\Middleware\Authenticate::class,
    ]);

4) then create a 'config' folder and add an 'auth.php' file with contents shown in the readme

5) then run the install commands shown in the main Laravel docs

The rest should be fairly straightforward, basically I added the Passport stuff to my User model, created a protected route and tested it with Postman.

	$app->group(['middleware' => 'auth:api'], function () use ($app) {
	    $app->get('/user', function () {
	    	return "fish";
	    });
	});

Couple of gotchas; 

for some reason it didn't generate the APP_KEY when it did the install so I had to manually create a random 32 char string

the client_id is the Primary Key in the database and the client_secret is exactly as it is in the database.

**Comment by dusterio** [comment]
Thanks for the comment - I did all this stuff myself but forgot to put it in the README, it's there now!

Minimum stability option shouldn't be important anymore - Lumen/Laravel 5.3 is officially released now, so it's a stable release.

And the APP_KEY bug has been annoying me for a while now, Lumen doesn't have any out-of-the-box solution to generate one, and it doesn't even complain about it properly! :) I should try to make a PR in the Lumen repo

**Comment by dusterio** [comment]
Oh yea, you are right - it's only Laravel 5.3 that was released, Lumen is not yet tagged as a version! They share a lot of stuff so I expected them to release about the same time

**Comment by himanshuakatalli** [comment]
Hi, I am confused here. Its first time I will be implementing oauth and I am a little new lumen/laravel.
I did everything written in readme.md. Now I have few doubts 

1. Do I have to call Passport::routes method if not then why ?

**Comment by dusterio** [comment]
@himanshuakatalli you don't need to because these routes are added by Lumen Passport in PassportServiceProvider. The reason we couldn't and shouldn't rely on Passport::routes() is that it adds Laravel-specific routes that require views and sessions

**Comment by himanshuakatalli** [comment]
@dusterio How do I use this ? Please don't mind, my question may sound a little naive to you because I am actually new to laravel/lumen. I am having difficulty understanding how to protect my routes using this auth, how tokens are made, when are they made. If it is possible can you please write here a general flow that should happen when we try accessing a route protected by passport.

**Comment by paolopiccinini** [comment]
You have to register middelware in youre routes. For the other question debugger is your friend :). I try to make a littel flow for password grant:
1) Laravel\Passport\Http\Controllers\AccessTokenController -> issueToken 
2) League\OAuth2\Server\AuthorizationServer -> respondToAccessToken
3)League\OAuth2\Server\Grant\PasswordGrant -> respondToAccessToken
4)League\OAuth2\Server\Grant\AbstractGrant -> issueToken
5)Laravel\Passport\Bridge\AccessTokenRepository -> getNewToken
6)League\OAuth2\Server\AuthorizationServer (we are returing in this call at point 2 calling generateHttpResponse)
7)League\OAuth2\Server\ResponseTypes\BearerTokenResponse (here we call AccessToken -> convertToJWT) ..., 

Hope this helps.

**Comment by himanshuakatalli** [comment]
@paolopiccinini @dusterio 

Request to post route 'oauth/token' resulting in methodnotallowed exception. But I did artisan route:list, the particular route is present in registered routes list.
