### ISSUE TITLE
custom token TTL /oauth/token with 'password' grant_type not working anymore?

### ISSUE THREAD

**Issue by DCdeBrabander** [dusterio/lumen-passport#11]
Does your update takes custom TTL of tokens into account? 

I see the following in the issueToken() method (in AccessTokenController):
````
$this->server->enableGrantType(
                $this->makePasswordGrant(), LumenPassport::tokensExpireIn(null, $clientId)
            );
````

I, am using in bootstrap/app.php:
````
\Laravel\Passport\Passport::tokensExpireIn(\Carbon\Carbon::now()->addSeconds(env('API_ACCESS_TOKEN_TTL', 600)));
\Laravel\Passport\Passport::refreshTokensExpireIn(\Carbon\Carbon::now()->addDays(30));
````

But my response is:
````
"body": {
    "refresh_token": "isQRZ82dGu61x.....",
    "access_token": "eyJ0eXAiOiJKV1Q.....",
    "token_type": "Bearer",
    "expires_in": 3155673600
  },
````

` "expires_in": 3155673600` is not 600, what is going wrong?

.env var:
`API_ACCESS_TOKEN_TTL=600`

**update**
refreshing token still works with custom TTL (expires_in)

**Comment by dusterio** [comment]
You are absolutely right, fallback to Laravel Passport value wasn't correct - this should be fine now, can you try again with updated version of Lumen Passport?

**Comment by DCdeBrabander** [comment]
Seems to be working again, thanks.
