### ISSUE TITLE
Cannot reduce scope on refresh token

### ISSUE THREAD

**Issue by Syafiqq** [dusterio/lumen-passport#110]
While I try to refresh token with a reduced scope, the generated token still produced the same scope as the old one. 
##### Step to reproduce 
1. You can review this [test](https://github.com/Syafiqq/lumen-passport-tests-001/blob/067fe20ec1216da0877ed2522b96871f4cd1bde5/tests/feature/api/grant/RefreshGrantTest.php#L112)
2. You can compare [Lumen-Passport](https://github.com/Syafiqq/lumen-passport-tests-001) with [Laravel-Passport](https://github.com/Syafiqq/laravel-passport-tests-001). Just `clone` it, configure `.env`, run `cmds/recreate-db.sh`. and run the test.
3. Here the example test result using lumen. all test passed when using laravel with passport. ![image](https://user-images.githubusercontent.com/9932470/62264753-80534b00-b44b-11e9-9e31-e76f3bbe3816.png)

**Comment by dusterio** [comment]
@Syafiqq I think it's a known "feature" of Laravel Passport. If the same user/subject had access tokens before - the new access token will have the same scopes. Therefore, when changing privileges/scopes for a user, you have to purge old tokens from the database

**Comment by Syafiqq** [comment]
Oh, I never thought of that. Thank you for the explanation. 👍

**Comment by Syafiqq** [comment]
Just curious, how to do that?

**Comment by Syafiqq** [comment]
Oh, I just figure it out that lumen test needs to call `$this->refreshApplication();` in order to differentiate between requests. If I don't call that function, the incoming request always holds the previous request parameter.
