### ISSUE TITLE
i got 401 Unauthorized

### ISSUE THREAD

**Issue by amaher-developer** [dusterio/lumen-passport#113]
I using lumen framwork and it work fine when project on local host but i got 401 Unauthorized this error on AWS online server

**Comment by EntrepreneurAJ** [comment]
Steps to check
1) The remote version is up to date
2) The database migration is in place
3) The encryption keys are available
4) The credentials are correct
5) The token issued is the right one (Local and Remote tokens will be different)

**Comment by salvationarinze** [comment]
I have been battling with this for days now. I am hosting dreamhost. I have tried to modify .htaccess file as recommended on stackoverflow, all to no avail

**Comment by dusterio** [comment]
@salvationarinze I think most of us stopped using Apache many years ago ;)

**Comment by salvationarinze** [comment]
I know. We are systematically migrating but for now, what do you advise?
