### ISSUE TITLE
route not mounted

### ISSUE THREAD

**Issue by Abdussamii** [dusterio/lumen-passport#122]
I am using lumen 6.2 with lumen-passport 0.2.15 when I try to get token it usually say error 404 which I attribute to route not loading. I also try to get version which is a shipped route but I could not. Please help me as I am on this issue some days now.

**Comment by Manbec** [comment]
Did you solve this @Abdussamii ?I'm having the same issue

**Comment by Abdussamii** [comment]
Sorry I could not solve the issue as I tried to do so. I later used laravel 6 with passport for my project then.
