### ISSUE TITLE
Refresh Token is Missing

### ISSUE THREAD

**Issue by caktoy** [dusterio/lumen-passport#124]
I tried follow every step and then try to access `{my_url}/oauth/token` with body `application/json` like this:
```
{
	"grant_type": "client_credentials",
	"client_id": "1",
	"client_secret": "Dq5E8lfuPel1Ym33qqt9Yy5wIRe4NGzOVNsYhZQP"
}
```
But the response only contains `token_type`, `expires_in`, and `access_token` without **`refresh_token`** attribute. Is there something step I need to do. Please help.

**Comment by PatsyMR** [comment]
![image](https://user-images.githubusercontent.com/6842190/90417103-ea4f8a00-e078-11ea-8aa2-2a76db461529.png)
 Here is the way I am loggin in, maybe you can try this way
