### ISSUE TITLE
FatalErrorException in AccessTokenController.php line 27: syntax error, unexpected '['

### ISSUE THREAD

**Issue by Tellurian7** [dusterio/lumen-passport#13]
Hi,

I'm using PHP v 5.6.28 and i get this error when i call oath/token (POST) : 

> Syntax at line 27 in vendor\dusterio\lumen-passport\src\Http\Controllers\AccessTokenController.php is not supported 

```
$clientId = array_key_exists('client_id', (array) $request->getParsedBody())
                ? ((array) $request->getParsedBody())['client_id'] : null;
```

Replace by 

```
$requestBodyArray = ((array) $request->getParsedBody());
$clientId = array_key_exists('client_id', $requestBodyArray) ? $requestBodyArray['client_id'] : null;
```

and it works.

Do i need a specific PHP configruation or something ? (array casting in ternary condition ?)
Thanks.

**Comment by Tellurian7** [comment]
I'm using the latest version of lumen-passport, without the PSR7 code and the array casting in ternary condition fail (syntax error)

**Comment by paolopiccinini** [comment]
I'm so sorry. I've linked the wrong issue. #10

**Comment by Tellurian7** [comment]
No problem :) I didn't notice this issue was already reported.

**Comment by himanshuakatalli** [comment]
@paolopiccinini @Tellurian7 @dusterio 

I am facing 405 Method not allowed exception on /oauth/token route with grant type password.

**Comment by paolopiccinini** [comment]
what are log saying? go in yourApp/storage/logs
