### ISSUE TITLE
  array_keys() expects parameter 1 to be array, null given when install

### ISSUE THREAD

**Issue by yogaxv** [dusterio/lumen-passport#138]
when i run php artisan passport:install, lumen give me error 

>  In InstallCommand.php line 34:
> array_keys() expects parameter 1 to be array, null given

**Comment by dusterio** [comment]
@yogaxv passport:install is a Laravel Passport command, it's not a part of this package?

**Comment by iameronmosele** [comment]
@yogaxv i had this issue this morning the proper fix is to add the auth.php in the config file from the setup process. config => auth.php


`return [
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => \App\User::class
        ]
    ]
];`

**Comment by keremkurtulus** [comment]
> @yogaxv i had this issue this morning the proper fix is to add the auth.php in the config file from the setup process. config => auth.php
> 
> `return [
> 'defaults' => [
> 'guard' => 'api',
> 'passwords' => 'users',
> ],
> 
> ```
> 'guards' => [
>     'api' => [
>         'driver' => 'passport',
>         'provider' => 'users',
>     ],
> ],
> 
> 'providers' => [
>     'users' => [
>         'driver' => 'eloquent',
>         'model' => \App\User::class
>     ]
> ]
> ```
> 
> ];`
don't forget add `$app->configure('auth');`  to bootstrap/app.php file.
