### ISSUE TITLE
Got internal server error Class 'Zend\Diactoros\Response' not found

### ISSUE THREAD

**Issue by tomg65** [dusterio/lumen-passport#144]
Hi,

in a new lumen 8 project i got this error on POST to /oauth/token:

Class 'Zend\Diactoros\Response' not found

in vendor/dusterio/lumen-passport/src/Http/Controllers/AccessTokenController.php (line 34)

.... `use Zend\Diactoros\Response as Psr7Response;`
....
.... `return $this->server->respondToAccessTokenRequest($request, new Psr7Response);`

Best Thomas

**Comment by gonzariosm** [comment]
zendframework/zend-diactoros is **abandoned**, you can change to **laminas/laminas-diactoros**

Is you need a simple solution, you can follow this steps.

1. in root project folder **composer require laminas/laminas-diactoros** 
2. Edit file vendor/dusterio/lumen-passport/src/Http/Controllers/AccessTokenController.php and search **use Zend\Diactoros\Response as Psr7Response;** and replace with **use Laminas\Diactoros\Response as Psr7Response;**

**Comment by dusterio** [comment]
@gonzariosm what about backward compatibility? will this work with older versions?

**Comment by gonzariosm** [comment]
sorry @dusterio i do not know because only test in Lumen 8.

**Comment by tailastra** [comment]
works fine for me, thanks @gonzariosm

**Comment by dusterio** [comment]
@gonzariosm ok I created a new version 0.3.1 just to be safe, thanks for the report

**Comment by tomg65** [comment]
> @gonzariosm ok I created a new version 0.3.1 just to be safe, thanks for the report

perfect - thank you very much
