### ISSUE TITLE
I am using lument-passport migrate cmd not working

### ISSUE THREAD

**Issue by navaneetharajan** [dusterio/lumen-passport#145]
I am using lumen 7.x version.  I refer this link:https://github.com/dusterio/lumen-passport. 
Migrate and install Laravel Passport

# Create new tables for Passport
php artisan migrate

# Install encryption keys and other necessary stuff for Passport
php artisan passport:install - Run this cmd i am facing issue like this
**issus: There are no commands defined in the "passport" namespace.**

**Comment by altugaykut** [comment]
I'm currently using lumen 8.x version and I **have to add** `composer require laravel/passport` to add passport functionality into php artisan, maybe you may need to install as well.
