### ISSUE TITLE
Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

### ISSUE THREAD

**Issue by aldoetobex** [dusterio/lumen-passport#147]
Hello, 

I've composer update my lumen 8 then lumen-passport isn't working now. If i comment error, everything works fine.

Error : 

exception: "ErrorException"
file: ".../vendor/lcobucci/jwt/src/Builder.php"
line: 151
message: "**Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.**"

Composer Update : 

 - Updating illuminate/contracts (v8.15.0 => v8.16.0): Downloading (100%)        - Updating illuminate/collections (v8.15.0 => v8.16.0): Downloading (100%)      - Updating illuminate/support (v8.15.0 => v8.16.0): Downloading (100%)          - Updating illuminate/pipeline (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/filesystem (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/container (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/console (v8.15.0 => v8.16.0): Downloading (100%)          - Updating illuminate/queue (v8.15.0 => v8.16.0): Downloading (100%)         
  - Updating illuminate/session (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/http (v8.15.0 => v8.16.0): Downloading (100%)         
  - Updating illuminate/auth (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/cookie (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/encryption (v8.15.0 => v8.16.0): Loading from cache
  - Updating lcobucci/jwt (3.3.3 => 3.4.0): Downloading (100%)         
  - Updating dragonmantank/cron-expression (v3.0.2 => v3.1.0):Downloading (100%)  - Updating illuminate/bus (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/broadcasting (v8.15.0 => v8.16.0): Downloading (100%)     - Updating illuminate/cache (v8.15.0 => v8.16.0): Downloading (100%)         
  - Updating illuminate/config (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/hashing (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/log (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/pagination (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/testing (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/translation (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/validation (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/events (v8.15.0 => v8.16.0): Loading from cache
  - Updating illuminate/view (v8.15.0 => v8.16.0): Loading from cache

**Comment by kerberus01** [comment]
Hi, I encountered the same error with lumen 8. I really hopping to get an update. Thanks in advanve
