### ISSUE TITLE
Call to undefined method Lcobucci\\JWT\\Token\\Plain::getClaim()

### ISSUE THREAD

**Issue by lloricode** [dusterio/lumen-passport#148]
package | version
----------- | -------------
php | 7.4.11
dusterio/lumen-passport | 0.3.1
laravel/passport | 10.1.0
lcobucci/jwt | 4.0.0

when updating to `laravel/passport v10.1.0`:
```
Call to undefined method Lcobucci\\JWT\\Token\\Plain::getClaim()
```

notice it update also `lcobucci/jwt` to `^4.0`
https://github.com/lcobucci/jwt/releases/tag/4.0.0

our temporary fix is add this to project composer.json
```json
 "lcobucci/jwt": "^3.4"
```
since laravel passport allow this
```json
"lcobucci/jwt": "^3.4|^4.0",
```

**Comment by aldoetobex** [comment]
Hi @lloricode, I encountered the same error. Thanks for your temporary fix solution

**Comment by damiotanjayson** [comment]
After trying this solution out it still returns

Call to undefined method Lcobucci\\JWT\\Token\\Plain::getClaim()

any alternatives?

**Comment by chris-doehring** [comment]
Unfortunetly, the workaround does not work when you want to use php 8. I created #150 which will fix the issue.

**Comment by AliRazaLilani** [comment]
if anyone still getting this error use this `$verifiedIdToken->claims()->get('sub')` instead of this `$verifiedIdToken->getClaim('sub')`
