### ISSUE TITLE
Apache users

### ISSUE THREAD

**Issue by paolopiccinini** [dusterio/lumen-passport#15]
it seems that apache discards the Authorization header if it is not a base64 encoded user/pass combo. See there https://github.com/tymondesigns/jwt-auth/wiki/Authentication.
Today i've faced this iusse. Maybe this saves a little bit of time to someone else. Just put in .htaccess, or apache config the following lines:

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**Comment by DCdeBrabander** [comment]
@paolopiccinini I also mentioned this per mail to @dusterio and it is mentioned in https://github.com/dusterio/lumen-passport/issues/9 since I also had some problems setting up

**Comment by dusterio** [comment]
Thanks for the hint, I will put this in the README shortly!

**Comment by DCdeBrabander** [comment]
@dusterio thanks, hopefully after that, future users will have much less problems setting up Passport in Lumen.  😄
