### ISSUE TITLE
token expire at now work

### ISSUE THREAD

**Issue by Rasoul-Karimi** [dusterio/lumen-passport#153]
hi 
my token expire an not work! i set LumenPassport::tokensExpireIn(Carbon::now()->addDays(30)); but expire tokin in 30 minet!

**Comment by stevefreedev** [comment]
Hi bro, did you put your client id on the second parameter?

// Second parameter is the client Id
LumenPassport::tokensExpireIn(Carbon::now()->addYears(50), 2); 
If you don't specify client Id, it will simply fall back to Laravel Passport implementation.
