### ISSUE TITLE
Error 400, error": "invalid_grant"

### ISSUE THREAD

**Issue by fapasv** [dusterio/lumen-passport#157]
Hi! everyone... and help! when I'm trying to login, API always return
"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
![image](https://user-images.githubusercontent.com/3285975/110491706-269b1400-80b7-11eb-9a40-3d4ec3ae4b89.png)

**Comment by santilorenzo** [comment]
Not sure if this issue is related to library but anyway, if could be either one of these:

- the client_id - client_secret pair don't match with each other
- the id-secret pair isn't for a password_client but for a personal_access_client (check those columns in the oauth_clients table)
- the password is wrong

**Comment by ruchisheth** [comment]
change grant_type to client_credentials'

**Comment by straube** [comment]
> change grant_type to 'client_credentials'

@ruchisheth I was able to get a token using this grant type. However, the token doesn't work. It seems `password` grant is really the right option but it doesn't work. I tried a lot of different solutions but nothing worked. 😞

**Comment by straube** [comment]
I finally was able to figure this out. I added a field to my `users` table literally called `username`. However, Passport tries to find users by email. Just adding a custom `findForPassport` method to my `User` class fixed the issue. And that's documented: https://laravel.com/docs/8.x/passport#customizing-the-username-field

**Comment by doncadavona** [comment]
Double check that the user's password is hashed in the database.

As for me, I forgot to hash new user registrations:

```php
public function register(RegisterRequest $request)
{
    $user = User::create($request->all()); // The password is not hashed

    return response()->json($user, 200);
}
```

Solution:

```php
public function register(RegisterRequest $request)
{
    $user = User::create(
        collect($request->all())
            ->merge(['password' => bcrypt($request->password)]) // The password is hashed
            ->toArray()
	);

    return response()->json($user, 200);
}
```

Perhaps to avoid this common issue, may we default the "password" term to be hashed by default when stored in the database.

**Comment by Arslan1122** [comment]
your password field is shouldn't be empty, if you want to login and get access token token without password past the code in your user model

`public function validateForPassportPasswordGrant($password)
    {
        return true;
    }`
