### ISSUE TITLE
NotFoundHttpException

### ISSUE THREAD

**Issue by MikeAlbela** [dusterio/lumen-passport#160]
Hi guys,
I followed every step on the instruction from installation to User model but when I tried to access it http://localhost:8000/oauth/token it is showing me error 404 NotFoundHttpException. 
I am pretty sure I've done everything on the instruction but one thing I am not sure of is the registering the routes, what I did is put this "\Dusterio\LumenPassport\LumenPassport::routes($this->app);" in the boot() function in AuthServiceProvider.php file

**Comment by santilorenzo** [comment]
You need to put this line in the AuthServiceProvider:
```
use Illuminate\Support\ServiceProvider;
public function boot()
{
        LumenPassport::routes($this->app->router);
}
```

**Comment by MikeAlbela** [comment]
Hello,
I already have that. here's my AuthServiceProvider

<?php

namespace App\Providers;

use App\Models\User;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Boot the authentication services for the application.
     *
     * @return void
     */
    public function boot()
    {
        \Dusterio\LumenPassport\LumenPassport::routes($this->app->router);
        // Here you may define how you wish users to be authenticated for your Lumen
        // application. The callback which receives the incoming request instance
        // should return either a User instance or null. You're free to obtain
        // the User instance via an API token or any other method necessary.

        $this->app['auth']->viaRequest('api', function ($request) {
            if ($request->input('api_token')) {
                return User::where('api_token', $request->input('api_token'))->first();
            }
        });
    }
}

**Comment by santilorenzo** [comment]
Did you uncomment/insert these lines in bootstrap/app.php?
```
$app->register(App\Providers\AuthServiceProvider::class);
$app->register(\Laravel\Passport\PassportServiceProvider::class);
$app->register(\Dusterio\LumenPassport\PassportServiceProvider::class);
```

**Comment by MikeAlbela** [comment]
Yes, I did uncomment those lines in bootstrap/app.php but still it's showing error 404 when I tried to access http://localhost:8000/oauth/token to generate a key.

**Comment by MikeAlbela** [comment]
Finally solved the issue. Seems like the instructions are bit incomplete if it's being followed by a newbie in lumen/laravel like me.
This link helped me to solved the issue: https://medium.com/@misteryomi/integrating-laravel-passport-in-your-lumen-project-with-example-1c2b8719c30
