### ISSUE TITLE
getting error on install passport in lumen 9 

### ISSUE THREAD

**Issue by darshanmultiqos** [dusterio/lumen-passport#170]
Hello 
I am installing the lumen 9 versions then I install passport getting an error so how can I install passport in lumen 9?
![lumenError](https://user-images.githubusercontent.com/94344697/154230490-8fde2ab1-7c62-4e04-9a03-64df308204b7.png)

**Comment by EdulimaProg** [comment]
Push of "dev-master"
something like "composer require dusterio/lumen-passport *"

**Comment by dusterio** [comment]
I just tagged it as a version
