### ISSUE TITLE
not support lumen 9

### ISSUE THREAD

**Issue by Rasoul-Karimi** [dusterio/lumen-passport#172]
hi
i have a error on lumen 9

`LumenPassport::routes($this->app, ['prefix' => 'v1/oauth']);

  Call to undefined method Laravel\Lumen\Application::group()  

`

**Comment by iriartmaxim** [comment]
i have the same problem.

**Comment by raulquintana** [comment]
With Lumen (9.0.2) (Laravel Components ^9.0)

```php
// bootstrap/app.php

$app->register(App\Providers\AuthServiceProvider::class);
```

```php
// app/Providers/AuthServiceProvider.php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AuthServiceProvider extends ServiceProvider {

    public function boot() {
        \Dusterio\LumenPassport\LumenPassport::routes($this->app->router, ['prefix' => 'v1/oauth']);
    }

}
```

---

@Rasoul-Karimi markdown code block please

````
```php
YOUR_CODE_HERE
```
````

**Comment by Rasoul-Karimi** [comment]
@raulquintana
this is not a true 

is issues in file: Dusterio\LumenPassport and LumenPassport.php in  lumen version on line 67 and your answer is not ok

**Comment by raulquintana** [comment]
@Rasoul-Karimi can you check it again?

**Comment by Rasoul-Karimi** [comment]
this is a difficult way, my friend! :))
this package needs to update and support lumen 9,  just this!
i don't know where is the admin of this package, and why don't update this repository
@dusterio

**Comment by beeards** [comment]
Closes #172; 

✅  **WORKS W LUMEN 9** following @raulquintana steps without issue.

_* Maybe README.md can be improved._

**Comment by dusterio** [comment]
@beeards @Rasoul-Karimi @raulquintana can somebody make a PR? :)

**Comment by Rasoul-Karimi** [comment]
hi 
@beeards

please look at to :

 Dusterio\LumenPassport and LumenPassport.php in lumen version on line 67 and your answer is not ok

 and fix it

**Comment by beeards** [comment]
@dusterio you got it here #173 👌 with @raulquintana & @Rasoul-Karimi indications.

**Comment by dusterio** [comment]
@beeards nice one, thanks!

**Comment by chitos07** [comment]
error still exist
