### ISSUE TITLE
Call to undefined method Laravel\Lumen\Routing\Router::middleware()

### ISSUE THREAD

**Issue by kng-caoxuanson** [dusterio/lumen-passport#184]
I am using lumen version 10

If I add this code to the bootstrap/app.php file it gives an error

`$app->register(Laravel\Passport\PassportServiceProvider::class);`

Error information: Call to undefined method Laravel\Lumen\Routing\Router::middleware()

help me.

**Comment by ekopras18** [comment]
same error, I think lumen 10 is not yet supported

**Comment by ekopras18** [comment]
see this [https://github.com/dusterio/lumen-passport/pull/182](url), work for me

**Comment by Jozef-Virag** [comment]
inside AuthServiceProvider.php method boot()
put this code : 
`Passport::$registersRoutes = false;`

**Comment by kng-caoxuanson** [comment]
> see this [https://github.com/dusterio/lumen-passport/pull/182](url), work for me

Great. Thank you very much.

> inside AuthServiceProvider.php method boot()
> put this code :
> `Passport::$registersRoutes = false;`

Great. Thank you very much.
