### ISSUE TITLE
Passport Vue Components

### ISSUE THREAD

**Issue by medienverbinder** [dusterio/lumen-passport#19]
Passport comes originally with three Vue components for a default frontend.

=> https://laravel.com/docs/5.3/passport#frontend-quickstart

Is there a simple way to integrate these components for Lumen?

**Comment by dusterio** [comment]
These three routes depend on sessions and views – both things are absent in Lumen. Lumen is a framework for APIs so it's assumed there can't be a 'logged-in user'

**Comment by medienverbinder** [comment]
First of all: Thanks for the quick reply and your super work.

No sessions, no views .... o.k. makes sense. Basically, I'm looking for a convenient way to register users (email verification) and manage authentication. I do not need sessions, but a simple REST-Client (UI) to create users and/or manage token would be nice :-) Mhhh...Laravel + Passport brings it all, but it's a little oversized for a small project.
