### ISSUE TITLE
Compatible with Lumen 5.4

### ISSUE THREAD

**Issue by 4levels** [dusterio/lumen-passport#23]
Hi,

is this library compatible with Lumen 5.4?

Kind regards and keep up the great work!  

PS. I came from esbenp's implementation in Lumen 5.0/5.1, via the updated oauth2 implementation from lucadegasperi/oauth2-server-laravel in 5.2 and now via the Laravel Passport implementation with Lumen 5.3

**Comment by dusterio** [comment]
I haven't checked yet - I will check shortly. If it's not - I will make it compatible! :) You can track the status in this issue

**Comment by 4levels** [comment]
Hi Denis,

I'm just from testing a cloned version of your repo and so far everything seems to work, including the scope and scopes middleware from Laravel's Passport library.

If you want, I can create a PR from my fork (I did nothing more than updating the versions in composer.json)

Kind regards and thank you for the swift reply!

Erik

**Comment by dusterio** [comment]
Thanks, I copied the lines from your composer.json :)
