### ISSUE TITLE
Set refresh token lifetime

### ISSUE THREAD

**Issue by codedge** [dusterio/lumen-passport#24]
Hi,

Laravel passport also allows to set the refresh token lifetime via `refreshTokensExpireIn`.
Is there any way to do this in this package as well or am I missing sth.?

Cheers!

**Comment by dusterio** [comment]
Sure, just use standard Laravel Passport method: Passport::refreshTokensExpireIn()

**Comment by Carlosfdev** [comment]
See my AuthServiceProvider if you want an example

```
<?php

namespace App\Providers;

use Carbon\Carbon;
use Dusterio\LumenPassport\LumenPassport;
use Illuminate\Support\ServiceProvider;
use Laravel\Passport\Passport;

class AuthServiceProvider extends ServiceProvider{
    public function register(){
    }
    public function boot(){
        $dayAfter = Carbon::now('Europe/Madrid')->addHours(24);
        Passport::tokensExpireIn($dayAfter);
        LumenPassport::allowMultipleTokens();
    }
}
```

**Comment by dusterio** [comment]
Just add Passport::refreshTokensExpireIn($dayAfter); in the boot() method?

**Comment by codedge** [comment]
@dusterio 
Ah, thanks. I just thought because your package provides a `LumenPassport::tokensExpireIn` it also provides a `LumenPassport::refreshTokensExpireIn`.

Anyway, I'll use the refreshTokensExpireIn method from the original package.

Cheers!
