### ISSUE TITLE
Deprecated function revokeOtherAccessTokens

### ISSUE THREAD

**Issue by aluferraz** [dusterio/lumen-passport#25]
Hi,

First of all, congratiolations for your package, it is really helpful !

I see that in the "Dusterio\LumenPassport\Http\Controllers\AccessTokenController" class you have the revokeOtherAccessTokens method, which calls the passport standard method revokeOtherAccessTokens.

However, the passport standard method "revokeOtherAccessTokens" is now deprecated and the source code does nothing more.. I couldn't find a quick replace for this method, but I saw this in the comments:

`/**
     * Revoke all of the access tokens for a given user and client.
     *
     * @deprecated since 1.0. Listen to Passport events on token creation instead.
     *
     * @param  mixed  $clientId
     * @param  mixed  $userId
     * @param  bool  $prune
     * @return void
     */
    public function revokeOtherAccessTokens($clientId, $userId, $except = null, $prune = false)
    {
        //
    }`

Could you please help me to get this to work again ?

Thanks !

**Comment by dusterio** [comment]
Try using the last development version (download from GitHub directly, not via composer)?

I just copy/pasted old Laravel code directly in the controller - it should work

**Comment by aluferraz** [comment]
Wow, that was fast ... It works just fine!

Thanks a lot !
