### ISSUE TITLE
'config/auth.php' file

### ISSUE THREAD

**Issue by miguelsmuller** [dusterio/lumen-passport#27]
I'm using lumen 5.4 and I'm having a hard time making an initial configuration, I have no idea where the 'config/auth.php' file is.

Is it because of the laravel version?

**Comment by DCdeBrabander** [comment]
You will need to create it yourself in the config/ directory :-)

An example of the contents: 

´´´
 return [
        'defaults' => [
            'guard' => 'api',
            'passwords' => 'users',
        ],

        'guards' => [
            'api' => [
                'driver' => 'passport',
                'provider' => 'users',
            ],
        ],

        'providers' => [
            'users' => [
                'driver' => 'eloquent',
                'model' => \App\User::class
            ]
        ]
    ];

´´´
