### ISSUE TITLE
Route Prefix

### ISSUE THREAD

**Issue by andrew-s** [dusterio/lumen-passport#29]
I noticed the original Laravel Passport package supports prefixing the routes - however, in the lumen-passport package it looks like the routes are hardcoded into PassportServiceProvider. More than happy to provide a PR but wanted to get an idea of implementation?

Did you want it to read from a config file or a static function call.

**Comment by dusterio** [comment]
Hmm, if it's implemented in Laravel Passport - the best approach IMHO would be to try to do it the same way (eg. if they use a static call - we use a static call). For consistency reasons - making it easier to switch between the two

**Comment by andrew-s** [comment]
Added the PR request, it is a somewhat breaking change as it now requires you to call ```LumenPassport::routes($app);``` however, so does Laravel/passport

**Comment by desyncr** [comment]
@andrew-s Could it be done in a backward compatible way for `0.1.x`?, Otherwise it'd require to bump to `1.x`.

**Comment by andrew-s** [comment]
I think it would make more sense to bump to 1.x otherwise, you'd be overwriting existing routes and that could become messy.

@desyncr No problem at all, happy to help

**Comment by andrew-s** [comment]
@desyncr @dusterio Do you guys need anything else for this?
