### ISSUE TITLE
Add middleware to routes of PassportServiceProvider

### ISSUE THREAD

**Issue by yokovaski** [dusterio/lumen-passport#31]
Hi,

I want to add middleware to the routes defined in PassportServiceProvider. I have tried to override the routes in /routes/web.php:
`$app->post('/oauth/token', [
        'middleware' => 'reject',
        'uses' => '\Dusterio\LumenPassport\Http\Controllers\AccessTokenController@issueToken',
    ]);`
This is throwing a 500 at me without a error message. I am currently clueless about what is going wrong.

I do not know if it is at all possible to add middleware to package defined routes and can't find any good solutions to my problem. Who is able to help me? :)

**Comment by desyncr** [comment]
Take a look at [here](https://github.com/dusterio/lumen-passport/issues/29) and [here](https://github.com/dusterio/lumen-passport/pull/30) where a route prefixing feature was implemented. I believe you can add your middleware configuration there.

**Comment by yokovaski** [comment]
Ah, I overlooked this merge because the latest release is from February. Thanks for the answer!
I added `"dusterio/lumen-passport": "dev-master",` to my composer.json and `Dusterio\LumenPassport\LumenPassport::routes($app, [
    'prefix' => 'api/v1/protected',
    'middleware' => 'reject',
]);` at the end of my bootstrap/app.php. 
It works perfectly now!

**Comment by desyncr** [comment]
Should be a new release soon? @dusterio
