### ISSUE TITLE
Call to undefined method Dusterio\LumenPassport\LumenPassport::routes()

### ISSUE THREAD

**Issue by muhammadnm** [dusterio/lumen-passport#32]
have this in my composer.json
```
"require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.4.*",
        "vlucas/phpdotenv": "~2.2",
        "dusterio/lumen-passport": "^0.1.9"
    },
```
there're few methods missing in LumenPassport.php and RouteRegistrar.php file missing

I've used following command to get this in
`$ composer require dusterio/lumen-passport`

**Comment by desyncr** [comment]
There is not release for the changes you're mentioning (routing registrar) see https://github.com/dusterio/lumen-passport/compare/0.1.9...master

You may use `@dev` meanwhile, although is not an option for production.

**Comment by dusterio** [comment]
@muhammadnm I have just tagged it as 0.2.0, try to update version in your composer.json and run 'composer update'
