### ISSUE TITLE
 Undefined method Illuminate\Auth\RequestGuard::handle()

### ISSUE THREAD

**Issue by oliveira-filipe** [dusterio/lumen-passport#33]
Hello,
I'm using dusterio/lumen-passport in the version ^ 0.2.0, in Lumen 5.4; Xampp, Apache, Win 10.

I followed the instructions available in the README

My .htaccess is as follows:
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

I have the following route with middlware 'auth':
```
$app->get('/passport-test', function(){
  return true;
})->middleware('auth');
```

But every time I access it, I get the following error:
`Fatal error: Call to undefined method Illuminate\Auth\RequestGuard::handle() in C:\xampp\htdocs\my-app\vendor\illuminate\auth\AuthManager.php on line 294`
Am I doing something stupidly wrong?

**Comment by edersoares** [comment]
2

**Comment by Hindua88** [comment]
I fixed it by.
$app->group(['middleware' => 'auth:api'], function($app)
{
    $app->get('/user/info', function() {
        $user = app('auth')->guard()->user();
        return response()->json($user);
    });
});

Note: You must set APP_KEY=xxx in .env file

**Comment by edersoares** [comment]
Thank you @Hindua88 I forgot the APP_KEY. It's work!
