### ISSUE TITLE
I get unsupported_grant_type error

### ISSUE THREAD

**Issue by efrainepayco** [dusterio/lumen-passport#39]
{
    "error": "unsupported_grant_type",
    "message": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check the `grant_type` parameter"
}

I get this error when I put my /oauth/token route using postman

Any solution?
Cheers!

**Comment by dusterio** [comment]
What exactly are you sending? What value of grant_type are you sending?

**Comment by efrainepayco** [comment]
<a href="https://ibb.co/gOhusv"><img src="https://thumb.ibb.co/gOhusv/Screenshot_105.png" alt="Screenshot_105" border="0"></a>

Here my parameters

**Comment by dusterio** [comment]
Hmm, first of all, these shouldn't be sent as query parameters, it should be a POST request with body parameters (form data)

**Comment by efrainepayco** [comment]
Thanks bro!

The problem was solved, I had bad estructured the way that I sent parameters, correct way is body with form-data

**Comment by MattWohler** [comment]
Also, make sure the header is set as `application/json`. Silly me. Postman has made me lazy.
