### ISSUE TITLE
Can not pass callback to LumenPassport::routes

### ISSUE THREAD

**Issue by maximzasorin** [dusterio/lumen-passport#40]
Method LumenPassport::routes needs to be modified for ability to take `$callback` argument as in Laravel\Passport::routes.

For example:
```
Dusterio\LumenPassport\LumenPassport::routes($app, $callback, $options);
```

This will allow configure only necessary routes.

**Comment by ronnie-depp** [comment]
same problem. the actual problem is this. cannot pass it `$app` @maximzasorin @dusterio @dcdebrabander

**Comment by dusterio** [comment]
@maximzasorin routes() method is practically identical to Laravel Passport routes() method, Laravel Passport got only two parameters as well? $callback can be a function or an app container
