### ISSUE TITLE
Can access other pages without Authorization

### ISSUE THREAD

**Issue by kiddyatreides** [dusterio/lumen-passport#42]
why I can access other page without Authorization ? i already put Dusterio\LumenPassport\LumenPassport::routes($app); in Web Routes.

![screenshot 230](https://user-images.githubusercontent.com/19512705/28419827-7856beaa-6d8a-11e7-8dcc-189a13f8e95f.png)

But as you can see here, otherpage are didn't authenticated.

**Comment by dusterio** [comment]
Did you add auth:api middleware to this route?

**Comment by kiddyatreides** [comment]
@dusterio i didn't. How to add them and where i should to add them? in the routes?

**Comment by kiddyatreides** [comment]
I add something like this and nothing .... 
Dusterio\LumenPassport\LumenPassport::routes($app, ['auth' => 'api'])

**Comment by desyncr** [comment]
Beware I'm using an older version. But this may help you out:

Register middleware in `bootstrap/app.php`
```php
 // Enable auth middleware (shipped with Lumen)
 $app->routeMiddleware([
     'auth' => App\Http\Middleware\Authenticate::class
 ]);

```

Use the registered middleware (`auth`) in your routes. In `routes/*.php`:
```php
$app->group(['middleware' => ['auth'], ...], ...
```

Then in `src/app/Http/Middleware/Authenticate.php` check the request is authenticated (not a guest):

```php

      public function handle($request, Closure $next, $guard = null)
      {
          // If there is no oauth return right away with 401 status code
          if ($this->auth->guard($guard)->guest()) {
              return response([
                  'status'  => 'error'
              ], 401);
          }
  
        return $next($request);
    }

```

**Comment by meankitguptagupta** [comment]
How can I check role of user before login?
