### ISSUE TITLE
Can not set different TTLs for different password clients

### ISSUE THREAD

**Issue by coffeemkr** [dusterio/lumen-passport#43]
I am using the function "LumenPassport :: tokensExpireIn (Carbon :: now () -> addDays (2), 2);" With the second client id parameter. The problem is that I always get the default value (one year).

I have tested "LumenPassport :: tokensExpireIn (Carbon :: now (-> addDays (2))"; Without the second client id parameter and working properly.

![1](https://user-images.githubusercontent.com/6395865/28551708-617a582c-70af-11e7-8e1f-bfa474524896.PNG)

![2](https://user-images.githubusercontent.com/6395865/28551753-9d2a638a-70af-11e7-98d8-d4c1efb536d2.PNG)

**Comment by dusterio** [comment]
I think this was broken by one of the pull requests (namespaces). It should be fixed now!
