### ISSUE TITLE
Rotes and parameters

### ISSUE THREAD

**Issue by henriqueweiand** [dusterio/lumen-passport#46]
Could you explain how to use the necessary routes and parameters?

**Comment by DCdeBrabander** [comment]
You have to choose yourself how you implement the given functionalities. 
There is an overview of available token routes in the readme of this package. 

I personally put a AuthController and middleware between the requester and the needed functionalities.
My AuthController uses Guzzle Client to request the given routes for fetching or authenticating.

You should check closed issues. Some people, including me, have talked about this.
