### ISSUE TITLE
Assign Specific Scopes to Token

### ISSUE THREAD

**Issue by Bpflugrad** [dusterio/lumen-passport#48]
Hi @dusterio.  I'm a newbie to Lumen and Laravel, but I'm really liking what I'm seeing.  Really love your package.

What I'm trying to do is when a user requesting Password grant specifies the scope as * check all available scopes and assign only those matching some criteria from the client to the token.  So let's say I have an array of roles in my User model that map to scopes, and a user has 2 of 3 of them, when requesting * the resulting token would only have the 2 that the user is allowed.

I think if I can do this then I can easily use \Laravel\Passport\Http\Middleware\CheckForAnyScope as my guard for most of my routes.

Thanks again!

**Comment by dusterio** [comment]
@Bpflugrad the problem with this approach, I think, is that tokens may be long living and you cannot modify/add scopes to an existing token later. so if you add a new scope later, all your existing tokens won't have access to it (unlike * that will always work)
