### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by wojlive** [dusterio/lumen-passport#54]
Hi, I have followed the documentation and installed the package + configured it. However when I getto one of the routes I get that I am not authorised. How do  I pass a token in the url in order  to be authorised?

**Comment by dusterio** [comment]
@wojlive It's an HTTP header in the following format: Authorization: Bearer {token}
This format is actually quickly becoming industry's standard

**Comment by wojlive** [comment]
thanks @dusterio could you give me an example of where to set it up the header? I am completely new to Lumen + API, I have an idea of how it works, but I am trying to implement one for practical understanding
