### ISSUE TITLE
Refresh Token Runtime Error

### ISSUE THREAD

**Issue by faizalpribadi** [dusterio/lumen-passport#59]
When i trying to refresh token on route `/oauth/token/refresh`  grant_type `refresh_token`, i got following this error message : `lumen.ERROR: RuntimeException: Session store not set on request.` , can you explain about this, or for refresh token does not support at this now ?

PING @dusterio

**Comment by desyncr** [comment]
@faizalpribadi I'm having the same issue. It seems `\Laravel\Passport\Http\Controllers\TransientTokenController@refresh` do uses session/cookies.

**Comment by dusterio** [comment]
Don't use TransientTokenController to refresh - that's something else. You can use the main route (POST /oauth/token) with grant_type set to 'refresh_token'. See 'Refreshing Tokens' section of the https://laravel.com/docs/5.5/passport Laravel Passport documentation

**Comment by desyncr** [comment]
Great! Thanks!
