### ISSUE TITLE
Why do we need this?

### ISSUE THREAD

**Issue by jeroenherczeg** [dusterio/lumen-passport#6]
Hi,

Thank you for your work, but I was searching for Lumen 5.3 and Passport and came here.
Why do we need a packages to make passport word with lumen?
Shouldn't this work out-of-the-box?
What are the problems?

Kind regards,
Jeroen

**Comment by desyncr** [comment]
AFAIK Laravel packages are not compatible with Lumen out-of-the-box.

**Comment by jeroenherczeg** [comment]
https://laracasts.com/discuss/channels/lumen/passport-for-lumen
