### ISSUE TITLE
Issue in Lumen 5.6

### ISSUE THREAD

**Issue by wasiqaftab** [dusterio/lumen-passport#66]
I am getting this error

`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager`

Can you please guide me how can i fix it

**Comment by CraigReeves1230** [comment]
I'm getting the exact same error. Followed the instructions to a tee.

**Comment by dusterio** [comment]
Sorry, you are getting this error when you do what exactly?
I've just tried installing this with Lumen 5.6 and so far I don't get any errors

**Comment by CraigReeves1230** [comment]
Simply sending a POST request to /oauth/token will trigger the error.

It doesn't matter what is put in the form data, it will still give the same
error.

I followed the instructions to a tee and it works perfectly in Lumen 5.4,
so it's probably something with the update.

**Comment by CraigReeves1230** [comment]
If you are unable to reproduce the error, I can post up here PHP files.

**Comment by CraigReeves1230** [comment]
I have not yet tried it in Lumen 5.5.

**Comment by dusterio** [comment]
There seems to be a bug in Laravel Passport that causes this, but I found a workaround, try putting this in any SP of yours:

    $this->app->singleton(\Illuminate\Hashing\HashManager::class, function ($app) {
        return new \Illuminate\Hashing\HashManager($app);
    });

**Comment by CraigReeves1230** [comment]
Thank brotha. I will try that when I get back to the house. You definitely
might want to update your instructions! :)

Btw, 5.6 is the only version I ran into this problem. 5.5 works just fine.

**Comment by dusterio** [comment]
Already did :))) It took me a while to upgrade to PHP 7.1 to test this :)

**Comment by Patskimoto** [comment]
Not sure if this is a bad solution or a solution that wouldn't even work as I haven't migrated to 5.6 yet but instead of requiring users to put that code snippet in manually can that registered the singleton go in PassportServiceProvider in the `Dusterio\LumenPassport` namespace?

**Comment by dusterio** [comment]
@Patskimoto you are right, I've just done that

**Comment by ThamanVelasquezBice** [comment]
This is unrelated to me, but just for the sake of cleaning up issues, could this issue be closed now? Or does it require a package update?

**Comment by dusterio** [comment]
@wolm sure, I modified the regex just now :) before 5.7 was released, I couldn't predict what's going to be needed hehe :))
