### ISSUE TITLE
Lumen 5.6 compatibility

### ISSUE THREAD

**Issue by AntoineDewaele** [dusterio/lumen-passport#68]
Hi there !

Is lumen-passport compatible with lumen 5.6 ?
On my side, impossible to run it.

`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\\Support\\Manager`

How can i fix that ?

Thx for your answer.

**Comment by dusterio** [comment]
Added support just now, please update the package and try again!
