### ISSUE TITLE
routes not mounted

### ISSUE THREAD

**Issue by rajaunleashed** [dusterio/lumen-passport#8]
Hi,

I followed all the steps but the routes are not mounted there in lumen route folder?
I didn't understand this line? I think I am doing something wrong after the passport:install command.

"Adding this service provider, will mount the following routes:" 
What's the meaning of this line?

**Comment by paolopiccinini** [comment]
The route are mounted in Dusterio\LumenPassport\PassportServiceProvider. passport:install configure the keys to use when generating token. passport:migrate generate the db-table requred from passport.

**Comment by rajaunleashed** [comment]
can you give me whole source code of lumen with running passport please? I tried thrice time But I failed.

**Comment by paolopiccinini** [comment]
https://github.com/dusterio/lumen-passport/blob/master/src/PassportServiceProvider.php

**Comment by rajaunleashed** [comment]
By the way thank you I have already found the source code but I whole lumen project with passport integrated. These are only files Dusterio have provided.

**Comment by rajaunleashed** [comment]
When I am installing the package it shows me the following message after installation of package.

phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
lcobucci/jwt suggests installing mdanter/ecc (Required to use Elliptic Curves based algorithms.)
league/oauth2-server suggests installing indigophp/hash-compat (Polyfill for hash_equals function for PHP 5.5)

**Comment by paolopiccinini** [comment]
those are only suggestion package. Nothing blocking. you can install them if you want or not.

**Comment by rajaunleashed** [comment]
Thank you man. I reached to the final stage. one more help please sorry for asking again and again. 

here is may route.php

<?php


$app->post('/oauth/token', '\Laravel\Passport\Http\Controllers\AccessTokenController@issueToken');

it gives me the error.
Class App\Http\Controllers\\Laravel\Passport\Http\Controllers\AccessTokenController does not exist

how to access those classes as they are in vendor folder?

**Comment by paolopiccinini** [comment]
passport routes are already configured. You just have to use them. They are already registered

**Comment by rajaunleashed** [comment]
Just WoW brother Thanks alot. its magic 👯‍♂️  nothing to do. Thanks @paolopiccinini  and @dusterio

**Comment by rajaunleashed** [comment]
How to issue token? Should I pass parameters with the the issueToken route?

**Comment by paolopiccinini** [comment]
For example
set the verb as post and the request body as 
{
	"username" : "yourEmail@email.com",
	"password" : "yourPassword",
	"client_id" :  "youClientId",
	"client_secret" : "yourClientSecret",
	"grant_type" : "password"
} 
of course you have to save in the db a user with email = "yourEmail@email.com" and "password" = "yourPassword", and a client.
You can read the doc for more info https://laravel.com/docs/5.3/passport#introduction

**Comment by rajaunleashed** [comment]
ok Thanks alot. :)

**Comment by kiddyatreides** [comment]
hello, i already follow all the steps but i have same issue here, it brings me http not found exception._. can you help me? i can't access the token, everytime i want to get the token with post localhost:8000/oauth/token and raw body i can't. It bring me to http not found exception. What happened?

**Comment by desyncr** [comment]
Did you registered the routes correctly? See https://github.com/dusterio/lumen-passport#registering-routes

**Comment by paolopiccinini** [comment]
you have to point in your application root

localhost:8000/oauth/token it's missing your app

localhost:8000/[app-root]/oauth/token

**Comment by ronnie-depp** [comment]
I'm having the same issue. I have tried Lumen 5.4 & 5.5. 
@desyncr I was unable to Register the Routes as you pointed out. Because when I pass $app to:
`Dusterio\LumenPassport\LumenPassport::routes($app);`
it gives me error saying $app is undefined. And when I replace $app with app()
`Dusterio\LumenPassport\LumenPassport::routes(app());`
it says that group method is undefined in `Dusterio\LumenPassport\LumenPassport::routes` line#83 as $callback->group is replaced by Laravel\Lumen\Application->group()

@paolopiccinini how to get the Application-Root? Please point out.

PLEASE HELP

**Comment by tdavincci** [comment]
try using
Dusterio\LumenPassport\LumenPassport::routes($router); 
instead of
Dusterio\LumenPassport\LumenPassport::routes($app);

**Comment by ahmdabos** [comment]
hello , i have same issue 
when i call  http://localhost/lumen-app/public/oauth/token
its give me NotFoundHttpException
this is how i register the route:
LumenPassport::routes($this->app);

**Comment by dusterio** [comment]
@ahmdabos what Lumen version are you using and what lumen-passport package version?

**Comment by jvgm** [comment]
I'm really having trouble @dusterio 
lumen is 5.4 and lumen passport is latest

Class App\Http\Controllers\\Dusterio\LumenPassport\Http\Controllers\AccessTokenController does not exist

**Comment by NathanMacedo** [comment]
@jvgm @dusterio  I'm having the same problem. 

Class App\Http\Controllers\Dusterio\LumenPassport\Http\Controllers\AccessTokenController does not exist

**Comment by tshwangq** [comment]
got same issue, I've to downgrade to 0.2.0 to avoid this

**Comment by dusterio** [comment]
@tshwangq @jvgm @NathanMacedo hmm that's very strange - I tested on both 5.4 and 5.5, my route:list displays correct namespace:
POST   | /oauth/token                             |            | \Dusterio\LumenPassport\Http\Controllers\AccessTokenController     | issueToken

Are you sure you have the lastest Lumen Passport? There was an issue from another PR that I fixed recently. 

If you are sure it's the latest version, can you show how and where you run LumenPassport::routes() call?

**Comment by sanjukaniyamattam** [comment]
Follow this link
https://github.com/dusterio/lumen-passport

Only one change you have to do is in the Registering Routes Step

1. Open AuthServiceProvider.php in your app/Providers folder, add
use Dusterio\LumenPassport\LumenPassport;

2. Inside the boot() function, add:
LumenPassport::routes($this->app->router, ['prefix' => 'v1/oauth']);

Also
In lumen by default below 2 lines are commented
$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);

Just uncomment it.
===================================================

If your php artisan route:list is not working then 

1. Run 
   composer require appzcoder/lumen-routes-list

2. Add service provider into /bootstrap/app.php file.
   $app->register(Appzcoder\LumenRoutesList\RoutesCommandServiceProvider::class);

3. Run composer dump-autoload

**Comment by ronnie-depp** [comment]
this is the similar issue with routes and might help someone depending on thier versions of Lumen, LaravelPassport and LumenPassport: 
https://github.com/dusterio/lumen-passport/issues/47
