### ISSUE TITLE
Allow publishing vendor migrations to base migrations directory

### ISSUE THREAD

**Issue by vaishnavmhetre** [dusterio/lumen-passport#90]
Request to allow publishing vendor migrations of oauth to base migrations directory.

This shall help eradicating the issue of dissimilar datatype of user_id.

Scenario: Projects using uuid type id as default instead of increments shall manually modify the datatype of user_id field to uuid in oauth migrations. 

Several tools are out there to help use vendor publish in Lumen. People like me working on Enterprise solutions using this repository for authentication shall be benifited.

**Comment by RafaelCorreaQuantik** [comment]
An optional way of doing this is updating the field instead of publishing and changing it's default, like so:

```
Schema::table('oauth_auth_codes', function (Blueprint $table) {
        $table->string("user_id");
});
```

**Comment by vaishnavmhetre** [comment]
> An optional way of doing this is updating the field instead of publishing and changing it's default, like so:
> 
> ```
> Schema::table('oauth_auth_codes', function (Blueprint $table) {
>         $table->string("user_id");
> });
> ```

Thanks for your response @RafaelCorreaQuantik . I manually copies the migrations and changed user_id type to uuid than string.

Closing the issue for no response for the request.
